// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SISGERED.API.Data;

#nullable disable

namespace SISGERED.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20261004055310_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SISGERED.API.entidades.Empresaaeaxterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NET")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Telefono")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmpresasExternas", (string)null);
                });

            modelBuilder.Entity("SISGERED.API.entidades.Intervecion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<DateTime>("Fechafin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fechainicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Administrador")
                        .HasColumnType("int");

                    b.Property<int>("ID_Empresaexterna")
                        .HasColumnType("int");

                    b.Property<int>("ID_Reporte")
                        .HasColumnType("int");

                    b.Property<int>("ID_personal")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Intervenciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Intervencion_ResponsableExclusivo", "([ID_personal] IS NOT NULL AND [ID_Empresaexterna] IS NULL) OR ([ID_personal] IS NULL AND [ID_Empresaexterna] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SISGERED.API.entidades.personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Cedula")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personal", (string)null);
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.ConjuntoResidencial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId")
                        .IsUnique();

                    b.ToTable("ConjuntosResidenciales");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntervecionId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int?>("ResidenteId")
                        .HasColumnType("int");

                    b.Property<int?>("RevisionId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntervecionId");

                    b.HasIndex("PersonalId");

                    b.HasIndex("ResidenteId");

                    b.HasIndex("RevisionId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Residente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ConjuntoResidencialId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ConjuntoResidencialId");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoRevision")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntervencionId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<string>("TipoRevision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntervencionId");

                    b.HasIndex("PersonalId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Revisiones");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("ConjuntoResidencialId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoUbicacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConjuntoResidencialId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.ConjuntoResidencial", b =>
                {
                    b.HasOne("SISGERED.shared.Entities.Administrador", "Administrador")
                        .WithOne()
                        .HasForeignKey("SISGERED.shared.Entities.ConjuntoResidencial", "AdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Reporte", b =>
                {
                    b.HasOne("SISGERED.API.entidades.Intervecion", "Intervecion")
                        .WithMany()
                        .HasForeignKey("IntervecionId");

                    b.HasOne("SISGERED.API.entidades.personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId");

                    b.HasOne("SISGERED.shared.Entities.Residente", "Residente")
                        .WithMany()
                        .HasForeignKey("ResidenteId");

                    b.HasOne("SISGERED.shared.Entities.Revision", "Revision")
                        .WithMany("Reportes")
                        .HasForeignKey("RevisionId");

                    b.HasOne("SISGERED.shared.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Reportes")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervecion");

                    b.Navigation("Personal");

                    b.Navigation("Residente");

                    b.Navigation("Revision");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Residente", b =>
                {
                    b.HasOne("SISGERED.shared.Entities.ConjuntoResidencial", "ConjuntoResidencial")
                        .WithMany()
                        .HasForeignKey("ConjuntoResidencialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConjuntoResidencial");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Revision", b =>
                {
                    b.HasOne("SISGERED.API.entidades.Intervecion", "Intervencion")
                        .WithMany()
                        .HasForeignKey("IntervencionId");

                    b.HasOne("SISGERED.API.entidades.personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SISGERED.shared.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Revisiones")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervencion");

                    b.Navigation("Personal");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Ubicacion", b =>
                {
                    b.HasOne("SISGERED.shared.Entities.ConjuntoResidencial", "ConjuntoResidencial")
                        .WithMany()
                        .HasForeignKey("ConjuntoResidencialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConjuntoResidencial");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Revision", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("SISGERED.shared.Entities.Ubicacion", b =>
                {
                    b.Navigation("Reportes");

                    b.Navigation("Revisiones");
                });
#pragma warning restore 612, 618
        }
    }
}
